# Generated by Django 2.2.26 on 2022-01-05 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumnx',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ingrese el nombre del alumnx', max_length=100)),
                ('num_cuenta', models.CharField(help_text='Ingrese el número de cuenta del alumnx', max_length=200)),
                ('email', models.EmailField(help_text='Ingrese el email del alumnx', max_length=200)),
                ('universidad', models.IntegerField(choices=[(1, 'Ibero León'), (2, 'Ibero Tijuana')], default=1)),
                ('asignatura', models.IntegerField(choices=[(1, 'Interculturalidad'), (2, 'Persona y Humanismo')], default=1)),
                ('ciclo', models.IntegerField(choices=[(1, 'Primavera 2022'), (2, 'Otro')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Segundo_parcial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calif_ensay_2do', models.DecimalField(decimal_places=1, help_text='Ingrese la calificación del ensayo (2do parcial)', max_digits=2)),
                ('calif_expo_2do', models.DecimalField(decimal_places=1, help_text='Ingrese la calificación de la exposición (2do parcial)', max_digits=2)),
                ('participacion_2do', models.IntegerField(default=0)),
                ('nombre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estudiantes.Alumnx')),
            ],
        ),
        migrations.CreateModel(
            name='Primer_parcial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calif_mono', models.DecimalField(decimal_places=1, help_text='Ingrese la calificación de la monografía (1er parcial)', max_digits=2)),
                ('calif_expo_1er', models.DecimalField(decimal_places=1, help_text='Ingrese la calificación de la exposición (1er parcial)', max_digits=2)),
                ('participacion_1er', models.IntegerField(default=0)),
                ('nombre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estudiantes.Alumnx')),
            ],
        ),
        migrations.CreateModel(
            name='Final',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calif_ensay_final', models.DecimalField(decimal_places=1, help_text='Ingrese la calificación del ensayo (3er parcial)', max_digits=2)),
                ('calif_expo_final', models.DecimalField(decimal_places=1, help_text='Ingrese la calificación de la exposición (3er parcial)', max_digits=2)),
                ('participacion_final', models.IntegerField(default=0)),
                ('nombre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estudiantes.Alumnx')),
            ],
        ),
        migrations.CreateModel(
            name='Autobiografia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autobiografia', models.DecimalField(decimal_places=1, help_text='Ingrese la calificación de la autobiografía', max_digits=2)),
                ('nombre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estudiantes.Alumnx')),
            ],
        ),
    ]
