# Generated by Django 2.2.26 on 2022-02-19 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0002_auto_20220219_0032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='primer_parcial',
            name='calif_expo_1er',
            field=models.DecimalField(decimal_places=1, max_digits=2),
        ),
        migrations.AlterField(
            model_name='primer_parcial',
            name='calif_mono',
            field=models.DecimalField(decimal_places=1, max_digits=2),
        ),
        migrations.AlterField(
            model_name='primer_parcial',
            name='participacion_1er',
            field=models.DecimalField(decimal_places=1, max_digits=2),
        ),
    ]
