# Generated by Django 2.2.26 on 2022-03-02 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0003_auto_20220219_0059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autobiografia',
            name='autobiografia',
            field=models.DecimalField(decimal_places=1, help_text='Ingrese la calificación de la autobiografía', max_digits=3),
        ),
        migrations.AlterField(
            model_name='final',
            name='calif_ensay_final',
            field=models.DecimalField(decimal_places=1, help_text='Ingrese la calificación del ensayo (3er parcial)', max_digits=3),
        ),
        migrations.AlterField(
            model_name='final',
            name='calif_expo_final',
            field=models.DecimalField(decimal_places=1, help_text='Ingrese la calificación de la exposición (3er parcial)', max_digits=3),
        ),
        migrations.AlterField(
            model_name='final',
            name='participacion_final',
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
        migrations.AlterField(
            model_name='primer_parcial',
            name='calif_expo_1er',
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
        migrations.AlterField(
            model_name='primer_parcial',
            name='calif_mono',
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
        migrations.AlterField(
            model_name='primer_parcial',
            name='nombre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='primer_par', to='estudiantes.Alumnx'),
        ),
        migrations.AlterField(
            model_name='primer_parcial',
            name='participacion_1er',
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
        migrations.AlterField(
            model_name='segundo_parcial',
            name='calif_ensay_2do',
            field=models.DecimalField(decimal_places=1, help_text='Ingrese la calificación del ensayo (2do parcial)', max_digits=3),
        ),
        migrations.AlterField(
            model_name='segundo_parcial',
            name='calif_expo_2do',
            field=models.DecimalField(decimal_places=1, help_text='Ingrese la calificación de la exposición (2do parcial)', max_digits=3),
        ),
        migrations.AlterField(
            model_name='segundo_parcial',
            name='participacion_2do',
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
    ]
