# Generated by Django 2.2.26 on 2022-03-28 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0004_auto_20220302_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='segundo_parcial',
            name='nombre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segundo_par', to='estudiantes.Alumnx'),
        ),
    ]
