# Generated by Django 2.2.26 on 2022-03-28 23:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0005_auto_20220328_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='final',
            name='nombre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='final_par', to='estudiantes.Alumnx'),
        ),
    ]
